### ISSUE TITLE
Feature request: maximum_depth filter.

### ISSUE THREAD

**Issue by r-plus** [DavidGoldman/InspectiveC#1]
I want to filter to log via call-tree depth just like Subjective-C's `SubjC_set_maximum_depth(size_t maximum_depth)` function.

**Comment by DavidGoldman** [comment]
Agreed, the depth does need to be limited. Would you prefer this to be absolute (i.e. it will never go past a depth of X) or relative to a hit (i.e. log up to hit, then up to X after)?

**Comment by r-plus** [comment]
Maybe relative.
My most often usage is to know what is called in method.

    -(void)method
    {
        InspectiveC_watchObject(self);
        %orig;
        InspectiveC_unwatchObject(self);
    }

**Comment by DavidGoldman** [comment]
I'll probably end up adding relative support. Anyways, I'm not sure how well that method works - it may skip over some calls, no? It would probably be better to watch the object earlier, register the selectors that you want to watch, and then modify [InspectiveC.mm#L477](https://github.com/DavidGoldman/InspectiveC/blob/master/InspectiveC.mm#L477) to use and instead of or.

**Comment by r-plus** [comment]
Oh, It's great for my usage!

**Comment by DavidGoldman** [comment]
The other question with relative support is what if hits nest - should it just be X after the first hit or X after the last hit? Probably makes sense to be the latter.

**Comment by r-plus** [comment]
Yes, I thought latter is better too.

**Comment by DavidGoldman** [comment]
Added support in v1.0.6-1 which is available here on my repo. You can update your InspCWrapper.m and use setMaximumRelativeLoggingDepth.

**Comment by r-plus** [comment]
Yah, thanks for your work👍
